# Generated by Django 5.0.1 on 2025-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Viewed", "Viewed"),
                    ("Shortlisted", "Shortlisted"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
