# Generated by Django 5.0.1 on 2025-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Viewed", "Viewed"),
                    ("Shortlisted", "Shortlisted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
